### PR TITLE
add '-split=floating_relative' option

### PR DESCRIPTION
**Pull request by orokasan**
This PR adds an option for opening denite's floating window near cursor position like popup-menu.

output
`:Denite -split=floating_relative neoyank register`

Now this option doesn't work with -auto-resize option.
I will support this later.

### CODE REVIEW

**Comment by Shougo** [comment]
> Now this option doesn't work with -auto-resize option.
> I will support this later.

OK.

**Comment by tex** [comment]
Have you tried to open filter buffer when floating_relative window is open?
I did and I think position of the filter buffer is not correct. It is shifted one character to right.
And if the filter buffer is opened top of cursor position the filter buffer position is totaly wrong.

**Comment by orokasan** [comment]
Sorry. I'll make PR for fix this problem.

**Comment by tex** [comment]
Awesome! Thanks! This floating_relative is great idea and I like it lot!

**Pull request merged**
