### PR TITLE
add some common vim normal mode text commands

### PR DESCRIPTION
**Pull request by sodiumjoe**
Let me know if anything's wrong, I'm a total python n00b

movement:
* b
* w
* e
* 0
* $
* h
* l

change:
* cc
* cw

delete:
* dd
* dw

append:
* a
* A

insert:
* I

### CODE REVIEW

**Comment by lambdalisue** [comment]
Do not touch files in prompt for implementing denite specific feature.

**Comment by sodiumjoe** [comment]
So I should move these all to `rplugin/python3/denite/ui/action.py`?

**Comment by lambdalisue** [comment]
Yes. Then I'll review if Shougo want but I'm a bit busy for now so ping me after mid of March in that case

**Comment by sodiumjoe** [comment]
Ok, I'll close this and reopen a new one. Thanks!

**Pull request closed without merging**
