### PR TITLE
Port 'isprint' function from Python itself to reduce Vim call.

### PR DESCRIPTION
**Pull request by lambdalisue**
- [x] Lint
- [x] License note

### CODE REVIEW

**Comment by Shougo** [comment]
The license agreement is too long.
Please move the function to another file.
Better is in neovim-prompt.

**Comment by lambdalisue** [comment]
It should be in denite's code while neovim-prompt did not port the target code but denite. I'll move it to an isolated file later :-]

2016年11月5日 12:34 +0900 に Shougo <notifications@github.com> は書きました:

**Comment by lambdalisue** [comment]
Done. @Shougo.

**Comment by Shougo** [comment]
LGTM

**Pull request merged**
