### PR TITLE
Call 'inputsave/inputrestore' on very outer-side

### LINKED ISSUE #169: Typeahead buffer is not properly redirected to Denite window
# Problems summary

Typeahead buffer is not properly redirected to Denite window.

## Expected

Typing quickly after executing `Denite` should not cause keystrokes to be applied to the current buffer. Instead, the keystrokes should be applied to the Denite buffer.

## Environment Information (Required!)

 * denite version(SHA1):

   020f232765c553d27ea3a68b0414733365b9d87b

 * OS:

   Arch Linux

 * Vim/neovim version:

   Vim 8.0238

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 25 2017 20:14:54)
Included patches: 1-238
Compiled by guns@…
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
+clientserver    +insert_expand   +packages        -toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        -perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python/dyn      +vreplace
+cscope          +lispindent      +python3/dyn     +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      +lua/dyn         +rightleft       +writebackup
+diff            +menu            +ruby/dyn        +X11
+digraphs        +mksession       +scrollbind      +xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      -mouseshape      +startuptime     +xsmp_interact
+eval            +mouse_dec       +statusline      +xterm_clipboard
+ex_extra        +mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax
+farsi           +mouse_netterm   +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-O1,--sort-common,--as-needed,-z,relro -L/usr/local/lib -Wl,--as-needed -o vim    -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lncurses -lelf -lnsl    -lacl -lattr -lgpm -ldl
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set runtimepath+=.
```

## The reproduce ways from neovim starting (Required!)

Execute vim with Denite and start typing `asdfasdf` quickly:

`$ vim -N -u init.vim -c 'Denite file_rec'`

Alternately, use `xdotool` to start typing after a brief delay (you may have to adjust the delay to properly see the race):

`$ (sleep 0.2; xdotool type ifoobar) & vim -N -u init.vim -c 'Denite file_rec'`

## Screen shot (if possible)

denite

## Suggestion

Calling `inputsave` earlier works:

```diff
diff --git a/rplugin/python3/denite/denite.py b/rplugin/python3/denite/denite.py
index 83c6123..d590ec0 100644
--- a/rplugin/python3/denite/denite.py
+++ b/rplugin/python3/denite/denite.py
@@ -95,6 +95,7 @@ class Denite(object):
             yield source.name, entire, partial
 
     def on_init(self, context):
+        self._vim.call('inputsave')
         self._current_sources = []
         for [name, args] in [[x['name'], x['args']]
                              for x in context['sources']]:
diff --git a/rplugin/python3/denite/prompt/prompt.py b/rplugin/python3/denite/prompt/prompt.py
index 24ccf19..a0c7b7d 100644
--- a/rplugin/python3/denite/prompt/prompt.py
+++ b/rplugin/python3/denite/prompt/prompt.py
@@ -198,7 +198,7 @@ class Prompt:
                 STATUS_PROGRESS, the prompt mainloop immediately terminated.
                 Returning None is equal to returning STATUS_PROGRESS.
         """
-        self.nvim.call('inputsave')
+        # self.nvim.call('inputsave')
 
     def on_update(self, status):
         """Update the prompt status and return the status.
```

### PR DESCRIPTION
**Pull request by lambdalisue**
This would fix #169

### CODE REVIEW

**Comment by lambdalisue** [comment]
Waiting @guns while my PC is too fast to confirm the issue.

**Comment by lambdalisue** [comment]
No. It won't work on Vim.

**Comment by guns** [comment]
Can confirm this addresses #169

**Comment by lambdalisue** [comment]
Thanks. Could you review and merge this @Shougo?

**Pull request merged**
