### PR TITLE
[RFC] allow quoted source arguments (ex. source:"!rg foobar" instead of source:!rg:foobar)

### PR DESCRIPTION
**Pull request by blankname**
There are still some problems to fix, but I want to find out if this feature is desirable before I spend more time on it.

### CODE REVIEW

**Comment by Shougo** [comment]
Please fix the CI errors.

```
autoload/denite/helper.vim:94:17: Use robust operators `==#` or `==?` instead of `==` (see Google VimScript Style Guide (Matching))

autoload/denite/helper.vim:94:41: Use robust operators `==#` or `==?` instead of `==` (see Google VimScript Style Guide (Matching))

autoload/denite/helper.vim:97:17: Use robust operators `==#` or `==?` instead of `==` (see Google VimScript Style Guide (Matching))

autoload/denite/helper.vim:97:41: Use robust operators `==#` or `==?` instead of `==` (see Google VimScript Style Guide (Matching))
```

**Comment by Shougo** [comment]
The documentation update is needed.

**Comment by blankname** [comment]
Added some docs and fixed known problems.
CI now passes.

**Comment by Shougo** [comment]
Merged.

**Pull request merged**
