### PR TITLE
add -immediately-1 option

### PR DESCRIPTION
**Pull request by tmn-o3**

### CODE REVIEW

**Comment by Shougo** [comment]
Please fix the conflict.
Why this feature is needed?
Please explain it.

**Comment by tmn-o3** [comment]
When I execute Denite tag for existing plural candidates, I'd like to choose a candidate on denite buffer.
But It has exactly one candidate, there is no need to open denite buffer.

**Comment by Shougo** [comment]
OK.

**Comment by hokorobi** [comment]
👍

**Pull request merged**
