### PR TITLE
Ack source

### PR DESCRIPTION
**Pull request by carlitux**
Same source as grep but using ack

### CODE REVIEW

**Comment by zchee** [comment]
@carlitux Ah, I don't totally understand denite implements, and not read the your PR.
But maybe can change the `grep` command to other command, like
```vim
call denite#custom#source('grep', 'command', ['pt', '--follow', '--nocolor', '--nogroup', '--hidden', '-g', ''])
```

@Shougo It's correct? denite.nvim will ignore(or not use) it even if I set this config?

**Comment by Shougo** [comment]
@carlitux Why do you add the command source commit?
It is not related Ack source.  Please create new PR for it.

And yes, the ack source is not needed.
You can change the grep command by `denite#custom#var()`.

**Comment by carlitux** [comment]
@Shougo sorry I didn't to correct use of branches

**Comment by carlitux** [comment]
@Shougo @zchee maybe changing the code on grep. It is not working as I need using my ackrc config.

With this pull request I can query like '--js React src' not only 'ack'

**Comment by Shougo** [comment]
I have added the additional arguments support in grep source.
You don't have to create new source.

**Pull request closed without merging**
