### PR TITLE
[WIP] Fix timer problems

### PR DESCRIPTION
**Pull request by Shougo**

### CODE REVIEW

**Comment by Shougo** [comment]
It fixes the performance problem in denite.nvim.

Please test.

**Comment by petobens** [comment]
There seems to be something wrong with the statusline. the focus switches from the filter buffer to the candidate buffer -> I expect it to always remain in the filter buffer:
denite-statusline

**Comment by petobens** [comment]
The status line also seems to report the wrong source: in the gif I'm running `Denite file/rec` and the statusline reports `fast_file_mru`:
denite-wrong-statusline

**Comment by delphinus** [comment]
I see it occurs with floating windows. The title of the terminal window corrupts in filtering.

**Comment by Shougo** [comment]
@petobens You need to upload the minimal vimrc.
If not, I will ignore your report.

**Comment by Shougo** [comment]
> There seems to be something wrong with the statusline. the focus switches from the filter buffer to the candidate buffer -> I expect it to always remain in the filter buffer:

Fixed.

**Comment by Shougo** [comment]
https://github.com/Shougo/denite.nvim/pull/677#issuecomment-508876087

I don't reproduce it and I have ignored your report due to my policy.

**Comment by Shougo** [comment]
Merged.

**Comment by petobens** [comment]
> I don't reproduce it and I have ignored your report due to my policy.

Consider the following minimal init.vim file:

```viml
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim_0d353ce
set runtimepath+=$DOTVIM/bundle/repos/github.com/vim-airline/vim-airline
filetype plugin indent on

call denite#custom#option('default', {
            \ 'auto_resize': 1,
            \ 'auto_resume': 1,
            \ 'statusline': 0,
            \ 'start_filter': 1,
            \ })

au FileType denite-filter call s:denite_filter_mappings()
function! s:denite_filter_mappings() abort
    inoremap <silent><buffer><expr> <ESC> denite#do_map('quit')
endfunction
```
Now, as in the GIF, open nvim and do:
1. Run `:Denite file/rec` and press `<ESC>`
2. Run `:Denite file/old` 

After 2. you will see that the statusline reports `file/rec` when I expect it to report `file/old`:

filerec-old

**Comment by Shougo** [comment]
Fixed.

**Comment by petobens** [comment]
Thank you

**Pull request merged**
