### PR TITLE
Add Socket class for TCP communication

### PR DESCRIPTION
**Pull request by rafi**
Example of integration: https://github.com/rafi/vim-denite-mpc

### CODE REVIEW

**Comment by HerringtonDarkholme** [comment]
I'm afraid adding this to core library make denite, at least possibly, not as secure as it currently is. Or makes it easier to be hacked. (For example, some plugin carelessly executes user input code)
All builtin sources require no network at all. If you need socket support, why not just putting it in your own source?

**Comment by rafi** [comment]
@HerringtonDarkholme I thought it can be a good feature and companion to Denite's `Process` class, which can also be unsecure, depending on the source vendor. Depends on source..

What do you think @Shougo ?

**Comment by HerringtonDarkholme** [comment]
I think Process is a must for all builtin sources. Also, Process is local to host machine but socket is easier for remote contact, which is more insecure.

**Comment by Shougo** [comment]
The socket feature is already implemented in Python.
So it is already insecure.  And all Vim plugins can execute `system()`.
They can be implemented as network access program easily.
You should not install malformed Plugin :-o

**Comment by rafi** [comment]
It will also be nice to have an HTTP communication object for web api's.

**Comment by Shougo** [comment]
I think it is nice feature.  Merged.

**Pull request merged**
