### PR TITLE
Add ability to access/modify Denite context

### PR DESCRIPTION
**Pull request by wilywampa**
This implements the ability to read/write to a Denite instance's context dictionary. I included (in the documentation I wrote but also below) an example that shows how to implement a key that reverses the order of candidates using only `denite#context#get`, `denite#context#set`, and `denite#custom#map`. I hope that shows how useful this can be.

```vim
function! ToggleReverse() abort " {{{
    let sorters = split(denite#context#get('sorters'), ',')
    if index(sorters, 'sorter_reverse') == -1
        call add(sorters, 'sorter_reverse')
    else
        call remove(sorters, index(sorters, 'sorter_reverse'))
    endif
    call denite#context#set('sorters', join(sorters, ','))
    return '<denite:redraw>'
endfunction " }}}
call denite#custom#map(
    \ 'insert',
    \ '<C-s>',
    \ 'ToggleReverse()',
    \ 'noremap expr'
    \)
```

### CODE REVIEW

**Comment by wilywampa** [comment]
Working on the regression test failure.

**Comment by Shougo** [comment]
I don't want to merge the feature.

* It is too long diff
* Non meaning Python code in context.vim

I will add the context change in the todo list.

**Comment by Shougo** [comment]
I should add denite_change_context mapping instead.

**Comment by Shougo** [comment]
@wilywampa For sorter_reverse, please create another PR. I will include it.

**Comment by wilywampa** [comment]
@Shougo Done. But I'd like to know what's too complex about this implementation. I thought it was fairly elegant. I also don't understand what "Non meaning Python code in vim.vim" is trying to say.

**Comment by wilywampa** [comment]
I'm not proud of the code in vim.vim, but I followed the example of what was already there to keep the function's variables in a temporary scope. I considered writing a simple class that would mean having less copy/pasted code but didn't think it was necessary for only 3 functions.

**Comment by Shougo** [comment]
Your example is very hacky.
If the feature is useful, it should be supported by denite core.

**Comment by Shougo** [comment]
get_context(), set_context() are hard to implement.  So your code is hacky

**Pull request closed without merging**
