### PR TITLE
Use nvim-yarp for Vim8

### PR DESCRIPTION
**Pull request by Shougo**
Please test for Vim8 users.

### CODE REVIEW

**Comment by hokorobi** [comment]
I tried replacing the denite that I am using now, but when I executed the `:Denite file/rec`, nothing appeared and the process was finished.
Windows 10 gVim 8.1.1040 Python 3.7.2 pynvim 0.3.2

$NVIM_PYTHON_LOG_LEVEL="DEBUG" log
```
2019-03-23 15:56:08,617 [INFO @ neovim_rpc_server.py:handle:84] 14552 - === socket opened ===
2019-03-23 15:56:08,617 [INFO @ neovim_rpc_server.py:handle:103] 14552 - received: b'[1,"neovim_rpc_setup"]\n'
2019-03-23 15:56:08,617 [INFO @ neovim_rpc_server.py:handle:120] 14552 - sending ["ex", "call neovim_rpc#_callback()"]
2019-03-23 15:56:08,648 [INFO @ neovim_rpc_server.py:process_pending_requests:364] 14552 - process_pending_requests
```

**Comment by Shougo** [comment]
Sorry.  It may not work in Windows.
It works on LInux environment.

**Comment by Shougo** [comment]
> I tried replacing the denite that I am using now, but when I executed the :Denite file/rec, nothing appeared and the process was finished.

Please test other sources.

**Comment by Shougo** [comment]
I don't know why it does not work in Windows.
Fortunately, you are very skilled programmer.
You can fix the problem.

**Comment by Shougo** [comment]
Windows maintainer is needed for denite.nvim.

@hokorobi Can you maintain it?

**Comment by hokorobi** [comment]
I understand that it does not work on Windows.
I would appreciate the invitation, but I will decline because I do not have the skills and time to be responsible for maintenance.
I will cooperate with you when I have time.

**Comment by Shougo** [comment]
I have merged https://github.com/Shougo/denite.nvim/pull/599 for Windows environment.
Please test the latest version.

**Comment by Shougo** [comment]
Merged.

**Comment by hokorobi** [comment]
It worked by setting `g:python3_host_prog`.

**Comment by Shougo** [comment]
OK.

**Pull request merged**
