### PR TITLE
Detect validly non-windows env on more sources

### PR DESCRIPTION
**Pull request by delphinus**
ref #355

the same as #354 on `directory_rec` and `file_rec`.

### CODE REVIEW

**Comment by Shougo** [comment]
The change breaks the behavior for me.

**Comment by Shougo** [comment]
I will fix the problem in the context initialization.

**Comment by delphinus** [comment]
I tried again.

* OS: macOS Sierra 10.12.6
* Vim: 8.0.844
  - brew install vim --with-python3 --with-override-system-vi
* vimrc

  ```vim
  let s:dein_dir = expand('/tmp/.cache/dein')
  let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'
  execute 'set runtimepath^=' . fnamemodify(s:dein_repo_dir, ':p')

  call dein#begin(s:dein_dir)
  call dein#add('Shougo/denite.nvim')
  call dein#end()

  if dein#check_install()
    call dein#install()
  endif

  filetype plugin indent on
  syntax enable
  ```

  ```sh
  rm -fr /tmp/.cache && git clone https://github.com/Shougo/dein.vim /tmp/.cache/dein/repos/github.com/Shougo/dein.vim
  vim -N -u minimal-vimrc -U NONE -i NONE
  ```

And I did `:Denite directory_rec`, and had this.

```
[denite] Traceback (most recent call last):
[denite]   File "<string>", line 9, in _temporary_scope
[denite]   File "/private/tmp/.cache/dein/.cache/minimal-vimrc/.dein/rplugin/python3/denite/ui/default.py", line 68, in start
[denite]     self._start(sources, context)
[denite]   File "/private/tmp/.cache/dein/.cache/minimal-vimrc/.dein/rplugin/python3/denite/ui/default.py", line 116, in _start
[denite]     self.gather_candidates()
[denite]   File "/private/tmp/.cache/dein/.cache/minimal-vimrc/.dein/rplugin/python3/denite/ui/default.py", line 636, in gather_candidates
[denite]     self._denite.gather_candidates(self._context)
[denite]   File "/private/tmp/.cache/dein/.cache/minimal-vimrc/.dein/rplugin/python3/denite/denite.py", line 63, in gather_candidates
[denite]     source.context, source)
[denite]   File "/private/tmp/.cache/dein/.cache/minimal-vimrc/.dein/rplugin/python3/denite/denite.py", line 72, in _gather_source_candidates
[denite]     candidates = source.gather_candidates(context)
[denite]   File "/tmp/.cache/dein/.cache/minimal-vimrc/.dein/rplugin/python3/denite/source/directory_rec.py", line 62, in gather_candidates
[denite]     context['__proc'] = Process(command, context, directory)
[denite]   File "/private/tmp/.cache/dein/.cache/minimal-vimrc/.dein/rplugin/python3/denite/process.py", line 25, in __init__
[denite]     cwd=cwd)
[denite]   File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 707, in __init__
[denite]     restore_signals, start_new_session)
[denite]   File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1333, in _execute_child
[denite]     raise child_exception_type(errno_num, err_msg)
[denite] PermissionError: [Errno 13] Permission denied
[denite] Please execute :messages command.
```

**Comment by Shougo** [comment]
I have fixed the problem.

**Pull request closed without merging**
