### PR TITLE
Add neovim floating window support

### LINKED ISSUE #517: Floating UI support
https://github.com/neovim/neovim/pull/6619

It is used by `-split=float`.

Note: neovim only

### PR DESCRIPTION
**Pull request by Shougo**
Fix #517

### CODE REVIEW

**Comment by Shougo** [comment]
Here is the example screenshot.
https://i.imgur.com/7gjXuhol.png

**Comment by agriffis** [comment]
@Shougo screenshot link doesn't seem to work?

**Comment by h-michael** [comment]
@agriffis
Can you see this?
https://i.imgur.com/7gjXuho_d.jpg?maxwidth=640&shape=thumb&fidelity=medium

**Comment by agriffis** [comment]
@h-michael yes, that worked, thanks

**Pull request merged**
