### PR TITLE
Improve command_history speed with lua

### PR DESCRIPTION
**Pull request by skt041959**
Hi Shougo,

I find the command_history source is too slow in my usage due to large number of histories.
The bottleneck should be lots of nvim api calls from Python client.

With my code, the speed has been improved a lot. Would you please take a review ?

Thanks

### CODE REVIEW

**Comment by tex** [comment]
Can lua be used to speed up MRU source too?

**Comment by skt041959** [comment]
> Can lua be used to speed up MRU source too?

@tex Do you mean which MRU source? I didn't find any in current Denite.nvim.

**Comment by tex** [comment]
Sorry, I meant Shougo's neomru.vim. Briefly looked at it and it heavily uses self.vim.call...

**Comment by Shougo** [comment]
> Sorry, I meant Shougo's neomru.vim. Briefly looked at it and it heavily uses self.vim.call...

In neomru, formatting is slow.

I have improved it.

**Comment by tex** [comment]
Thanks!!!

**Comment by Shougo** [comment]
I have fixed the compatibility problem in Vim8

**Pull request merged**
