### PR TITLE
[Feature Request][WIP] Add `jump` action to jump opened buffer window

### PR DESCRIPTION
**Pull request by pocke**
Hi

I need a new action for jumping to opened window for buffer source.

Action behavior
------

1. select a buffer by buffer source
1. get window number by `win_findbuf()` function.
    - If window exists, jump to the window by `win_gotoid()`
    - If window doesn't exist, fallback other action (Note: I've implement fallback to tabopen action, but I think the action should be selectable by user. But I don't know how to implement it.)

dac

Why work in progress
------

As mentioned above, user can't select the fallback action in this implementation. 
Could you tell me how to implement it?

### CODE REVIEW

**Comment by Shougo** [comment]
> I need a new action for jumping to opened window for buffer source.

It should be `switch` action instead of `jump`.

**Comment by Shougo** [comment]
> As mentioned above, user can't select the fallback action in this implementation.
Could you tell me how to implement it?

I think the default `tabopen` behavior is bad.
It should be `open` action.
But denite has not action customization support.

**Comment by Shougo** [comment]
unite.vim has `switch`, `tabswitch`, `splitswitch`, `vsplitswitch` actions.

**Comment by pocke** [comment]
Thanks for your help! I've implemented the `switch`, `tabswitch`, `splitswitch` and `vsplitswitch` features.
It works with buffer and file kind.

**Comment by pocke** [comment]
Sorry, I forgot to write the document. I'll write it now

**Comment by Shougo** [comment]
LGTM

**Pull request merged**
