### PR TITLE
fix some issues with `-split=floating_relative` option.

### PR DESCRIPTION
**Pull request by orokasan**
ref #759 

I'm trying to fix the problem with -auto-resize option.
Please wait for the merge.

### CODE REVIEW

**Comment by tex** [comment]
Tested this and it fixes wrong position of filter buffer when top of cursor position. 
The one char right shift still visible.

**Comment by orokasan** [comment]
Oops. fixed it.

**Comment by tex** [comment]
Beatiful. Tested it and works as expected. Great work!

**Comment by Shougo** [comment]
Merged.

**Comment by orokasan** [comment]
Can you reopen this PR?
I want to add to this PR some commits regarding to doc and -auto-resize option.

**Comment by Shougo** [comment]
Please create another PR for it.

**Comment by orokasan** [comment]
I got it. Thanks for your response.

**Comment by tex** [comment]
Sorry, that's me again. Try to -split=floating_relative with -start-filter. Filter buffer is placed wrongly.

**Comment by orokasan** [comment]
Sorry, I'll fix it.

**Pull request merged**
